function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "temp.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (editmode) {
jade_debug.unshift(new jade.DebugItem( 0, "temp.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "temp.jade" ));
buf.push("<div id=\"loader\" class=\"ui modal basic\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 2, "temp.jade" ));
buf.push("<div class=\"content\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "temp.jade" ));
buf.push("<div class=\"ui text loader\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, jade_debug[0].filename ));
buf.push("Loading");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 4, "temp.jade" ));
buf.push("<label class=\"loader\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "temp.jade" ));
buf.push("<form id=\"frm\" method=\"post\" data-type=\"evt\" action=\"/tinymce\" enctype=\"multipart/form-data\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 6, "temp.jade" ));
buf.push("<div id=\"ul_title\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 7, "temp.jade" ));
buf.push("<div class=\"title ui transparent input\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 8, "temp.jade" ));
buf.push("<input id=\"input-title\" name=\"title\" rows=\"1\" autofocus=\"autofocus\" required=\"required\" placeholder=\"标题\" class=\"title\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "temp.jade" ));
buf.push("<div id=\"date_src\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 10, "temp.jade" ));
buf.push("<div class=\"ui transparent input\">" + (jade.escape(null == (jade_interp = 'Date: ') ? "" : jade_interp)));
jade_debug.unshift(new jade.DebugItem( 11, "temp.jade" ));
jade_debug.unshift(new jade.DebugItem( 11, "temp.jade" ));
buf.push("<input id=\"input-date\" type=\"date\" name=\"date\" value=\"2016-01-01\"/>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 12, "temp.jade" ));
buf.push("<div class=\"ui transparent input\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 13, "temp.jade" ));
buf.push("<input id=\"input-source\" type=\"text\" name=\"source\" placeholder=\"文章/资料来源\" required=\"required\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "temp.jade" ));
buf.push("<div id=\"frm-body\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 15, "temp.jade" ));
buf.push("<div class=\"mymce-container\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 16, "temp.jade" ));
buf.push("<div id=\"input-body\">" + (null == (jade_interp = '<br>') ? "" : jade_interp));
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 17, "temp.jade" ));
buf.push("<div id=\"att\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 18, "temp.jade" ));
buf.push("<input id=\"input-att\" type=\"text\" name=\"att\" hidden=\"hidden\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 19, "temp.jade" ));
buf.push("<div id=\"ops\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 20, "temp.jade" ));
if ( !editmode)
{
jade_debug.unshift(new jade.DebugItem( 21, "temp.jade" ));
jade_debug.unshift(new jade.DebugItem( 21, "temp.jade" ));
buf.push("<div id=\"btn-upload\" class=\"ui labeled icon button basic teal small\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 21, jade_debug[0].filename ));
buf.push("提交");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 22, "temp.jade" ));
buf.push("<i class=\"icon send outline\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 23, "temp.jade" ));
buf.push("<div id=\"btn-img\" class=\"ui labeled icon button basic orange small\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 23, jade_debug[0].filename ));
buf.push("图片");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 24, "temp.jade" ));
buf.push("<i class=\"icon file image outline\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 25, "temp.jade" ));
buf.push("<div id=\"btn-att\" class=\"ui labeled icon button basic blue small\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 25, jade_debug[0].filename ));
buf.push("附件");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 26, "temp.jade" ));
buf.push("<i class=\"icon attach\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 27, "temp.jade" ));
buf.push("<div id=\"btn-cancel\" class=\"ui labeled icon button basic teal small\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("取消");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 28, "temp.jade" ));
buf.push("<i class=\"icon remove\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</i>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 29, "temp.jade" ));
buf.push("<div id=\"tips\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 29, jade_debug[0].filename ));
buf.push("tips:");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 30, "temp.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 30, jade_debug[0].filename ));
buf.push("可直接拖放插入图片");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();}.call(this,"editmode" in locals_for_with?locals_for_with.editmode:typeof editmode!=="undefined"?editmode:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "#loader.ui.modal.basic\r\n\t.content\r\n\t\t.ui.text.loader Loading\r\n\t\tlabel.loader\r\nform#frm(method=\"post\" data-type='evt' action=\"/tinymce\" enctype=\"multipart/form-data\")\r\n\t#ul_title\r\n\t\t.title.ui.transparent.input\r\n\t\t\tinput#input-title.title(name=\"title\" rows=\"1\" autofocus required placeholder=\"标题\")\r\n\t#date_src\r\n\t\t.ui.transparent.input= 'Date: '\r\n\t\t\tinput#input-date(type=\"date\" name=\"date\" value='2016-01-01')\r\n\t\t.ui.transparent.input\r\n\t\t\tinput#input-source(type=\"text\" name=\"source\" placeholder=\"文章/资料来源\" required)\r\n\t#frm-body\r\n\t\t.mymce-container\r\n\t\t\t#input-body!= '<br>'\r\n\t#att\r\n\t\tinput#input-att(type='text' name='att' hidden)\r\n#ops\r\n\tif !editmode\r\n\t\t#btn-upload.ui.labeled.icon.button.basic.teal.small 提交\r\n\t\t\ti.icon.send.outline\r\n\t#btn-img.ui.labeled.icon.button.basic.orange.small 图片\r\n\t\ti.icon.file.image.outline\r\n\t#btn-att.ui.labeled.icon.button.basic.blue.small 附件\r\n\t\ti.icon.attach\r\n\t#btn-cancel.ui.labeled.icon.button.basic.teal.small 取消\r\n\t\ti.icon.remove\r\n#tips tips:\r\n\tp 可直接拖放插入图片");
}
}